name: Sarahs Site
owner: Sarah Usher

baseurl: "" # the base url of your site
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  posts:
    permalink: /blog/:title
  teamposts:
    permalink: /blog/:title
  techposts:
    permalink: /blog/:title

exclude:
  - LICENSE
  - README.md
  - html-templates
